services:
  frontend:
    build:
      context: ./frontend
      target: dev
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
    develop:
      watch:
        # sync static content
        - path: ./frontend/package.json
          action: rebuild
          target: /app/package.json
        - path: ./frontend/pnpm-lock.yaml
          action: rebuild
          target: /app/pnpm-lock.yaml

  captcha-api:
    build:
      context: ./captcha-api
      target: dev
    restart: always
    ports:
      - 8080:8080
    environment:
      DATABASE_HOST: postgres
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: password
      DATABASE_DATABASE: captcha
    volumes:
      - ./captcha-api/src:/app/src
      - ./captcha-api/datasets:/app/datasets
    develop:
      watch:
        # sync static content
        - path: ./captcha-api/package.json
          action: rebuild
          target: /app/package.json
        - path: ./captcha-api/pnpm-lock.yaml
          action: rebuild
          target: /app/pnpm-lock.yaml
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: captcha
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
