services:
  frontend:
    build:
      context: ./frontend
      target: dev
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
    develop:
      watch:
        # sync static content
        - path: ./frontend/package.json
          action: rebuild
          target: /app/package.json
        - path: ./frontend/pnpm-lock.yaml
          action: rebuild
          target: /app/pnpm-lock.yaml

  # postgres:
  #   image: postgres:latest
  #   restart: always
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: flappybird
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #     - ./captcha-api/sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres-data:
